# Lab 7:  Reinforcement Learning

## Creating an environment

In [1]:
import gym

In [2]:
# Create a mapping to names of environments as specified in OpenAI Gym package

name_map = {'cartpole': 'CartPole-v1', 
            'mountaincar': 'MountainCar-v0',
            'pendulum': 'Pendulum-v0',
            'taxi': 'Taxi-v3',
            'lake': 'FrozenLake-v0'}

In [3]:
# Function to create a gym environment
def createEnv(input_env):
    # Create the environment and reset it
    env = gym.make(name_map[input_env])
    env.reset()
    # Iterate 1000 times
    for _ in range(1000):
        # Render the environment
        env.render()

        # take a random action
        env.step(env.action_space.sample()) 

In [4]:
# Cartpole environment
createEnv('cartpole')

C:\ProgramData\Anaconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [5]:
# Mountain Car environment
createEnv('mountaincar')

In [6]:
# Pendulum environment
createEnv('pendulum')

In [7]:
# Taxi environment
createEnv('taxi')

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| :

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | :_|
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B:_|
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B:_|
+---------+
  (Dropoff)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)


In [8]:
# Lake environment
createEnv('lake')


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFF

## Building a learning agent

In [9]:
import gym

In [10]:
# Create a mapping to names of environments as specified in OpenAI Gym package

name_map = {'cartpole': 'CartPole-v1', 
            'mountaincar': 'MountainCar-v0',
            'pendulum': 'Pendulum-v0'}

In [11]:
# Create the environment
env = gym.make(name_map['cartpole']) # Change this for different results

# Start iterating 
for _ in range(20):
    # Reset the environment
    observation = env.reset()

    # Iterate 100 times
    for i in range(100):
        # Render the environment
        env.render()

        # Print the current observation
        print(observation)

        # Take action 
        action = env.action_space.sample()

        # Extract the observation, reward, status and 
        # other info based on the action taken
        observation, reward, done, info = env.step(action)

        # Check if it's done
        if done:
            print('Episode finished after {} timesteps'.format(i+1))
            break
env.close()

[ 0.00366806 -0.04630301  0.03393614 -0.03616387]
[ 0.002742   -0.24189476  0.03321286  0.26703014]
[-0.0020959  -0.04726218  0.03855346 -0.01499494]
[-0.00304114  0.14728627  0.03825357 -0.29526885]
[-9.54175854e-05  3.41842574e-01  3.23481889e-02 -5.75646000e-01]
[ 0.00674143  0.14628245  0.02083527 -0.27295057]
[ 0.00966708 -0.0491305   0.01537626  0.02623037]
[ 0.00868447  0.1457676   0.01590086 -0.26156179]
[ 0.01159982 -0.04957768  0.01066963  0.03609374]
[ 0.01060827 -0.24485099  0.0113915   0.33212386]
[ 0.00571125 -0.44013322  0.01803398  0.62837722]
[-0.00309141 -0.63550215  0.03060153  0.92668467]
[-0.01580146 -0.4408065   0.04913522  0.64377337]
[-0.02461759 -0.24640254  0.06201069  0.36695931]
[-0.02954564 -0.05221406  0.06934987  0.09445591]
[-0.03058992  0.14184891  0.07123899 -0.17556632]
[-0.02775294 -0.05421643  0.06772766  0.1387123 ]
[-0.02883727  0.1398734   0.07050191 -0.13185827]
[-0.0260398   0.33391834  0.06786474 -0.4014922 ]
[-0.01936143  0.52801535  0.059834

[0.32024556 0.3511961  0.12304154 0.58290032]
[0.32726949 0.54439895 0.13469955 0.33136999]
[0.33815746 0.34764252 0.14132695 0.66331325]
[0.34511031 0.15086675 0.15459321 0.99694605]
[0.34812765 0.34362167 0.17453213 0.75653137]
[0.35500008 0.1465789  0.18966276 1.09865762]
Episode finished after 74 timesteps
[ 0.04223889 -0.02636899  0.01573263  0.03751376]
[ 0.04171151  0.16852386  0.01648291 -0.25016414]
[ 0.04508199  0.36340659  0.01147962 -0.53760278]
[ 5.23501186e-02  5.58365283e-01  7.27567560e-04 -8.26646610e-01]
[ 0.06351742  0.75347728 -0.01580536 -1.11910062]
[ 0.07858697  0.55856621 -0.03818738 -0.83141712]
[ 0.08975829  0.75418868 -0.05481572 -1.13586126]
[ 0.10484207  0.55982502 -0.07753294 -0.86086143]
[ 0.11603857  0.75591238 -0.09475017 -1.1768807 ]
[ 0.13115682  0.95212872 -0.11828779 -1.49769992]
[ 0.15019939  0.75862634 -0.14824179 -1.24417016]
[ 0.16537192  0.95530628 -0.17312519 -1.57937802]
[ 0.18447804  1.15201546 -0.20471275 -1.92067587]
Episode finished after

[ 0.04137534  0.17755969 -0.03658837 -0.34924861]
[ 0.04492653 -0.0170233  -0.04357334 -0.06832405]
[ 0.04458607 -0.21149433 -0.04493983  0.21029911]
[ 0.04035618 -0.40594587 -0.04073384  0.48847407]
[ 0.03223726 -0.21027361 -0.03096436  0.1832367 ]
[ 0.02803179 -0.01472259 -0.02729963 -0.11905127]
[ 0.02773734  0.18077964 -0.02968065 -0.42022045]
[ 0.03135293  0.3763093  -0.03808506 -0.72211059]
[ 0.03887912  0.18173428 -0.05252727 -0.44165401]
[ 0.0425138   0.37755868 -0.06136035 -0.75042139]
[ 0.05006498  0.57347082 -0.07636878 -1.06176519]
[ 0.06153439  0.76951635 -0.09760409 -1.37740697]
[ 0.07692472  0.57573958 -0.12515223 -1.11677529]
[ 0.08843951  0.38246229 -0.14748773 -0.86582565]
[ 0.09608876  0.57925045 -0.16480424 -1.20100759]
[ 0.10767377  0.77607487 -0.1888244  -1.54047732]
Episode finished after 21 timesteps
[-0.01602682  0.0475196   0.00957774 -0.02726486]
[-0.01507643 -0.14773838  0.00903245  0.2684245 ]
[-0.0180312   0.04725351  0.01440094 -0.0213959 ]
[-0.01708613  

## Example code for q-learning

In [12]:
import numpy as np
from random import randint
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

# defines the reward/link connection graph
R = np.matrix([[-1, -1, -1, -1,  0,  -1],
              [-1, -1, -1,  0, -1, 100],
              [-1, -1, -1,  0, -1,  -1],
              [-1,  0,  0, -1,  0,  -1],
              [ 0, -1, -1,  0, -1, 100],
              [-1,  0, -1, -1,  0, 100]])
Q = np.zeros_like(R)

The -1's in the table means there isn't a link between nodes. For example, State 'a' cannot go to State 'b'.

In [13]:
# learning parameter
gamma = 0.8

# Initialize random_state
initial_state = randint(0,4)

# This function returns all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act


# This function chooses at random which action to be performed within the range 
# of all the available actions.
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action

# This function updates the Q matrix according to the path selected and the Q 
# learning algorithm
def update(current_state, action, gamma):
    
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
    max_value = Q[action, max_index]
    
    # Q learning formula
    Q[current_state, action] = R[current_state, action] + gamma * max_value    

# Get available actions in the current state
available_act = available_actions(initial_state) 

# Sample next action to be performed
action = sample_next_action(available_act)

In [14]:
# Train over 100 iterations, re-iterate the process above).
for i in range(100):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
    
# Normalize the "trained" Q matrix
print ("Trained Q matrix: \n", Q/np.max(Q)*100)

Trained Q matrix: 
 [[  0.           0.           0.           0.          74.42455243
    0.        ]
 [  0.           0.           0.          59.33503836   0.
   93.09462916]
 [  0.           0.           0.          59.33503836   0.
    0.        ]
 [  0.          48.33759591  47.31457801   0.          74.42455243
    0.        ]
 [ 59.33503836   0.           0.          59.33503836   0.
   93.09462916]
 [  0.          74.42455243   0.           0.          74.42455243
  100.        ]]


In [15]:
current_state = 2
steps = [current_state]

while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size = 1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index

# Print selected sequence of steps
print ("Best sequence path: ", steps)

Best sequence path:  [2, 3, 4, 5]
